-- 코드를 입력하세요
SELECT UGB.TITLE,UGB.BOARD_ID,UG.REPLY_ID,UG.WRITER_ID,UG.CONTENTS,DATE_FORMAT(UG.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_REPLY UG on UGB.BOARD_ID = UG.BOARD_ID 
WHERE UGB.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY UG.CREATED_DATE ASC , UGB.TITLE ASC